name: iot_esp32_app
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.2.0"

dependencies:
  flutter:
    sdk: flutter

  shared_preferences: ^2.0.8
  cupertino_icons: ^1.0.2
  mqtt_client: ^10.0.0 
  flutter_local_notifications: ^16.0.0 
  audioplayers: ^5.2.0
  fl_chart: ^0.64.0
  provider: ^6.0.1
  sqflite: ^2.3.0
  permission_handler: ^11.0.1
  excel: ^2.1.0
  path_provider: ^2.1.1
  flutter_background_service: ^5.0.1
  flutter_foreground_task: ^6.1.2


flutter:
  uses-material-design: true

  assets:
    - assets/alarm_sound.mp3
